events {}

http {
    upstream auth_service {
        server auth-service:8080;
    }

    upstream quote_service {
        server quote-service:8080;
    }

    upstream ai_recommendation_service {
        server ai-recommendation-service:8000;
    }

    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth_service/;
        }

        location /quotes/ {
            proxy_pass http://quote_service/;
        }

        location /carriers/ {
            proxy_pass http://quote_service/;
        }

        location /zones/ {
            proxy_pass http://quote_service/;
        }

        location /ai/ {
            proxy_pass http://ai_recommendation_service/;
        }
    }
}
